alloy:
  alloy:
    configMap:
      content: |-
        logging {
          level = "info"
          format = "json"
        }


        loki.write "default" {
          endpoint {
            url = "http://loki-gateway.logging.svc.cluster.local:80/loki/api/v1/push"
          }
        }


        discovery.kubernetes "pod" {
          role = "pod"
          namespaces {
            names = ["production"]
          }
        }

        discovery.relabel "pod_logs" {
          targets = discovery.kubernetes.pod.targets

          rule {
            source_labels = ["__meta_kubernetes_namespace"]
            action = "replace"
            target_label = "namespace"
          }

          rule {
            source_labels = ["__meta_kubernetes_pod_name"]
            action = "replace"
            target_label = "pod"
          }

          rule {
            source_labels = ["__meta_kubernetes_pod_container_name"]
            action = "replace"
            target_label = "container"
          }

          rule {
            source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
            action = "replace"
            target_label = "app"
          }

          rule {
            source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_container_name"]
            action = "replace"
            target_label = "job"
            separator = "/"
            replacement = "$1"
          }

          rule {
            source_labels = ["__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
            action = "replace"
            target_label = "__path__"
            separator = "/"
            replacement = "/var/log/pods/*$1/*.log"
          }

          rule {
            source_labels = ["__meta_kubernetes_pod_container_id"]
            action = "replace"
            target_label = "container_runtime"
            regex = "^(\\S+):\\/\\/.+$"
            replacement = "$1"
          }
        }

        loki.source.kubernetes "pod_logs" {
          targets = discovery.relabel.pod_logs.output
          forward_to = [loki.process.filter_logs.receiver]
        }

        loki.process "filter_logs" {
          stage.drop {
            expression = ".*\"Path\":\\s\"\\/metrics.*\""
          }

          stage.multiline {
            firstline = "^info"
            max_wait_time = "3s"
          }

          stage.regex {
            expression = ".*\"Path\":\\s\"\\/api.*\""
          }

          stage.labels {
            values = {
              "Method" = "{{.Method}}",
              "Path" = "{{.Path}}",
              "StatusCode" = "{{.StatusCode}}",
              "ElapsedMilliseconds" = "{{.ElapsedMilliseconds}}",
            }
          }

          forward_to = [loki.write.default.receiver]
        }
