prometheus:
  extraScrapeConfigs: |
    - job_name: 'dotnet-tumble-backend'
      honor_timestamps: true
      scrape_interval: 1m
      scrape_timeout: 1m
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - tumble-backend.production.svc.cluster.local
    - job_name: kube-state-metrics
      honor_timestamps: true
      scrape_interval: 1m
      scrape_timeout: 1m
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - kube-state-metrics.kube-system.svc.cluster.local:8080
