prometheus:
  server:
    service:
      type: NodePort
      servicePort: 80

  extraScrapeConfigs: |
    - job_name: 'dotnet-tumble-backend'
      kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
              - development
      relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: development;tumble-backend-service;https
      metrics_path: /metrics
      scheme: https
      tls_config:
        insecure_skip_verify: true
