ingress-nginx:
  controller:
    allowSnippetAnnotations: true
    config:
      use-proxy-protocol: "true"
    service:
      annotations:
        service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
        service.beta.kubernetes.io/do-loadbalancer-hostname: "tumbleforkronox.com"
    extraArgs:
      default-ssl-certificate: "default/letsencrypt-prod"
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"
