keycloak:
  extraEnv: |
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"

  ingress:
    enabled: true
    ingressClassName: "nginx"
    servicePort: http
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: "nginx"

    rules:
      - host: "keycloak.tumbleforkronox.com"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - keycloak.tumbleforkronox.com
        secretName: letsencrypt-keycloak-prod

  postgresql:
    enabled: false
