ingress-nginx:
  controller:
    allowSnippetAnnotations: true
    config:
      use-proxy-protocol: "true"
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"
