{{- if .Values.tumble.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/server-snippet: |
      location /metrics {
        deny all;
        return 403;
      }
spec:
  rules:
    - host: app.tumbleforkronox.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tumble-backend
                port:
                  number: 80
  tls:
    - hosts:
        - app.tumbleforkronox.com
      secretName: letsencrypt-prod
{{- end }}