loki:
  deploymentMode: SingleBinary

  test:
    enabled: false

  lokiCanary:
    enabled: false

  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    storage:
      type: "filesystem"
    schemaConfig:
      configs:
        - from: "2024-01-01"
          store: tsdb
          index:
            prefix: loki_index_
            period: 24h
          object_store: filesystem
          schema: v13
    limits_config:
      allow_structured_metadata: true
      retention_period: 24h

  singleBinary:
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"

  read:
    replicas: 0
  backend:
    replicas: 0
  write:
    replicas: 0

  memcachedExporter:
    enabled: false
  resultsCache:
    enabled: false
  chunksCache:
    enabled: false
