apiVersion: v2
appVersion: 1.0.0
description: "Prometheus"
name: prometheus
version: 1.0.0
dependencies:
  - name: prometheus
    version: "25.27.0"
    repository: "https://prometheus-community.github.io/helm-charts"
