apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: development
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogIllXUjJaV1U2UjFWVk5uSjNVV2szYWl4ZFZDNVgiCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQp9
