apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: {{ .Release.Name }}-backend
          image: {{ .Values.tumble.backend_image }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ title .Release.Namespace | quote }}
            - name: DbConnectionString
              valueFrom:
                secretKeyRef:
                  name: tumble-backend-secrets
                  key: DbConnectionString
            - name: JwtEncKey
              valueFrom:
                secretKeyRef:
                  name: tumble-backend-secrets
                  key: Jwt__EncKey
            - name: JwtSigKey
              valueFrom:
                secretKeyRef:
                  name: tumble-backend-secrets
                  key: Jwt__SigKey
            - name: JwtExpiration
              valueFrom:
                secretKeyRef:
                  name: tumble-backend-secrets
                  key: Jwt__Expiration
            - name: AwsAccessKey
              valueFrom:
                secretKeyRef:
                  name: tumble-backend-secrets
                  key: Aws__AccessKey
            - name: AwsSecretKey
              valueFrom:
                secretKeyRef:
                  name: tumble-backend-secrets
                  key: Aws__SecretKey
            - name: TestUserEmail
              valueFrom:
                secretKeyRef:
                  name: tumble-backend-secrets
                  key: TestUser__Email
            - name: TestUserPass
              valueFrom:
                secretKeyRef:
                  name: tumble-backend-secrets
                  key: TestUser__Pass
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ghcr-secret
