apiVersion: v1
kind: ConfigMap
metadata:
  name: reverse-proxy-config
  namespace: monitoring
data:
  nginx.conf: |
    events {}
    http {
        server {
            listen 80;
            server_name monitoring.tumbleforkronox.com;

            location /grafana/ {
                proxy_pass http://grafana.monitoring.svc.cluster.local:80/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /prometheus/ {
                proxy_pass http://prometheus-server.monitoring.svc.cluster.local:80/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
