grafana:
  testFramework:
    enabled: false

  admin:
    existingSecret: "grafana-admin"
    userKey: admin-user
    passwordKey: admin-password

  serviceMonitor:
    enabled: false
    path: /metrics
    namespace: default
    interval: 30s
    scheme: http
    scrapeTimeout: 30s

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: "nginx"
    path: /
    pathType: Prefix
    hosts:
      - grafana.tumbleforkronox.com
    tls:
      - secretName: letsencrypt-prod
        hosts:
          - grafana.tumbleforkronox.com

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server.monitoring.svc.cluster.local:80
          access: proxy
          isDefault: true
        - name: Loki
          type: loki
          url: http://loki-gateway.logging.svc.cluster.local:80
          access: proxy

  dashboards:
    default:
      tumble-backend-dashboard:
        file: tumble-backend-dashboard.json

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
