name: Deploy Kubernetes Cluster on DigitalOcean

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.3'
        id: install

      - uses: azure/setup-helm@v4.2.0
        with:
          version: 'v3.15.3'
        id: install

      - name: Install Ansible Vault dependencies
        run: |
          ansible-galaxy collection install community.general
          ansible-galaxy install kubernetes.core

      - name: Load Ansible Vault secrets
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASS }}" > vault_pass.txt
        env:
          ANSIBLE_VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASS }}

      - name: Configure DigitalOcean
        run: |
          doctl auth init -t ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ../ansible/playbooks/deploy-prod.yml --vault-password-file vault_pass.txt
