name: Deploy to Production

on:
  push:
    paths:
      - "settings/prod/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: "latest"

      - name: Set up DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save do-ams3-k8s-tumble

      - name: Create Kubernetes Secrets
        run: |
          echo "${{ secrets.TUMBLE_BACKEND_SECRETS }}" > /tmp/tumble-backend-secrets.json

          kubectl create secret docker-registry ghcr-secret \
            --docker-server=ghcr.io \
            --docker-username=tumble-for-kronox \
            --docker-password=${{ secrets.GHCR_TOKEN }}

          kubectl create secret generic tumble-backend-secrets \
            --from-file=secrets.json=/tmp/tumble-backend-secrets.json

      - name: Deploy Middleware
        run: |
          for dir in settings/prod/middleware/*; do
            namespace=$(basename $dir)
            for component in $dir/*; do
              helm dependency update $component
              helm template $component -n $namespace | kubectl apply -f -
            done
          done

      - name: Deploy Backend
        run: |
          helm template settings/prod/backend --namespace production | kubectl apply -f -
